# Generated by Django 4.1.7 on 2023-02-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0002_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
